use super::{Scenario, dataset_admin, json, json_headers, step};
use serde_json::Value;

fn request(name: &str, method: &str, path: &str, body: Value) -> Scenario {
    step(
        "investigations",
        name,
        method,
        path,
        dataset_admin(),
        body,
        vec![],
    )
}

pub fn investigation_scenarios() -> Vec<Scenario> {
    let settings =
        json!({"name":"Research","model":"analysis","context":"Find unrecovered retries"});
    vec![
        step(
            "investigations",
            "00_without_auth",
            "GET",
            "/lens",
            json_headers(None),
            Value::Null,
            vec![],
        ),
        request("01_list", "GET", "/lens", Value::Null),
        request("02_read", "GET", "/lens/parity-lens", Value::Null),
        request("03_missing", "GET", "/lens/missing", Value::Null),
        request("04_runs", "GET", "/lens/parity-lens/runs", Value::Null),
        request(
            "05_run_detail",
            "GET",
            "/lens/parity-lens/runs/job",
            Value::Null,
        ),
        request(
            "06_reviews",
            "GET",
            "/lens/parity-lens/runs/job/reviews?after=2",
            Value::Null,
        ),
        request(
            "07_reviews_after",
            "GET",
            "/lens/parity-lens/runs/job/reviews?after=3",
            Value::Null,
        ),
        request(
            "08_missing_run",
            "GET",
            "/lens/parity-lens/runs/missing",
            Value::Null,
        ),
        request(
            "09_offset_negative",
            "GET",
            "/lens/parity-lens/runs?offset=-1",
            Value::Null,
        ),
        request(
            "10_offset_fraction",
            "GET",
            "/lens/parity-lens/runs?offset=1.5",
            Value::Null,
        ),
        request(
            "11_after_negative",
            "GET",
            "/lens/parity-lens/runs/job/reviews?after=-1",
            Value::Null,
        ),
        request("12_create_missing", "POST", "/lens", json!({})),
        request(
            "13_settings_empty",
            "POST",
            "/lens",
            json!({"name":"","model":""}),
        ),
        request(
            "14_settings_constraints",
            "POST",
            "/lens",
            json!({"name":"x","model":"x","source":"invalid","sample_percent":0,"sample_size":0,"lookback_hours":0,"interval_minutes":0,"concurrency":0,"monthly_budget":0}),
        ),
        request(
            "15_settings_checks",
            "POST",
            "/lens",
            json!({"name":"x","model":"x","checks":[{"id":"","instruction":"x","enabled":"bad"}],"filters":[{"key":"","value":""}]}),
        ),
        request(
            "16_settings_extra",
            "POST",
            "/lens",
            json!({"name":"x","model":"x","context":"ok","scope":{"all_teams":true}}),
        ),
        request(
            "17_settings_no_checks",
            "POST",
            "/lens",
            json!({"name":"x","model":"x","context":"  "}),
        ),
        request(
            "18_settings_duplicate_checks",
            "POST",
            "/lens",
            json!({"name":"x","model":"x","checks":[{"id":"c","instruction":"abc"},{"id":"c","instruction":"def"}]}),
        ),
        request(
            "19_settings_reserved_check",
            "POST",
            "/lens",
            json!({"name":"x","model":"x","checks":[{"id":"expected_behavior","instruction":"abc"}]}),
        ),
        request(
            "20_calendar_range",
            "POST",
            "/lens",
            json!({"name":"x","model":"x","context":"ok","lookback_hours":999999999999999_u64,"interval_minutes":999999999999999_u64}),
        ),
        request("21_no_model_provider", "POST", "/lens", settings.clone()),
        request(
            "22_invalid_execution",
            "POST",
            "/lens",
            json!({"name":"x","model":"x","context":"ok","execution_ids":["bad"]}),
        ),
        request(
            "23_run_missing_lens",
            "POST",
            "/lens/missing/runs",
            json!({}),
        ),
        request(
            "24_run_incomplete_window",
            "POST",
            "/lens/parity-lens/runs",
            json!({"start":"2026-01-01T00:00:00Z"}),
        ),
        request(
            "25_run_window_order",
            "POST",
            "/lens/parity-lens/runs",
            json!({"start":"2026-01-02T00:00:00Z","end":"2026-01-01T00:00:00Z"}),
        ),
        request(
            "26_run_agent_length",
            "POST",
            "/lens/parity-lens/runs",
            json!({"agent_name":"a".repeat(201)}),
        ),
        request(
            "27_run_no_provider",
            "POST",
            "/lens/parity-lens/runs",
            json!({}),
        ),
        request(
            "28_feedback_bad_status",
            "PATCH",
            "/lens/parity-lens/findings/finding",
            json!({"status":"invalid"}),
        ),
        request(
            "29_feedback_alias",
            "PATCH",
            "/lens/parity-lens/findings/old-finding",
            json!({"status":"resolved","reason":"fixed"}),
        ),
        request(
            "30_feedback_missing",
            "PATCH",
            "/lens/parity-lens/findings/missing",
            json!({"status":"dismissed"}),
        ),
        request(
            "31_settings_update",
            "PUT",
            "/lens/parity-lens",
            settings.clone(),
        ),
        request(
            "32_settings_pause",
            "PUT",
            "/lens/parity-lens",
            json!({"name":"Paused","model":"analysis","context":"Find unrecovered retries","enabled":false}),
        ),
        request("33_watch_skipped", "POST", "/lens/watch-all", Value::Null),
        request(
            "34_enable_no_provider",
            "PUT",
            "/lens/parity-lens",
            settings,
        ),
        request("35_cancel", "POST", "/lens/parity-lens/cancel", Value::Null),
        request(
            "36_cancel_again",
            "POST",
            "/lens/parity-lens/cancel",
            Value::Null,
        ),
        request(
            "37_run_detail_after_cancel",
            "GET",
            "/lens/parity-lens/runs/job",
            Value::Null,
        ),
        request(
            "38_offset_past_end",
            "GET",
            "/lens/parity-lens/runs?offset=50",
            Value::Null,
        ),
        request(
            "39_missing_cancel",
            "POST",
            "/lens/missing/cancel",
            Value::Null,
        ),
        request(
            "40_settings_coercion",
            "PUT",
            "/lens/parity-lens",
            json!({"name":"Research","model":"analysis","context":"Find unrecovered retries","enabled":"false","lookback_hours":"24","interval_minutes":15.0,"concurrency":true,"monthly_budget":"25.5","sample_percent":"50.5"}),
        ),
        request("41_read_final", "GET", "/lens/parity-lens", Value::Null),
    ]
}
