use super::bounded_string;

bounded_string!(AgentTestCaseExpected, 1, None);
bounded_string!(AgentTestCaseInput, 1, None);
bounded_string!(CheckId, 1, None);
bounded_string!(CheckInstruction, 3, None);
bounded_string!(CheckpointWorkingNotes, 1, None);
bounded_string!(EvidenceQuote, 1, None);
bounded_string!(ExtractionReasoning, 0, Some(800), default = "");
bounded_string!(FindingDescription, 10, None);
bounded_string!(FindingDraftDescription, 10, None);
bounded_string!(FindingDraftTitle, 3, None);
bounded_string!(FindingTitle, 3, None);
bounded_string!(IssueBriefProblem, 10, None);
bounded_string!(IssueBriefUserGoal, 3, None);
bounded_string!(IssueBriefWhatHappened, 3, None);
bounded_string!(LensSettingsModel, 1, None);
bounded_string!(LensSettingsName, 1, None);
bounded_string!(MetadataFilterKey, 1, None);
bounded_string!(MetadataFilterValue, 1, None);
bounded_string!(ModelRequestPrompt, 1, None);
bounded_string!(PythonAgentTurnExtractionCheckpoint, 1, None);
bounded_string!(PythonAgentTurnFindingsCheckpoint, 1, None);
bounded_string!(PythonRequestCode, 1, None);
bounded_string!(ReviewReasoning, 0, Some(800), default = "");
bounded_string!(ReviewSpanKind, 0, Some(40));
bounded_string!(ReviewSpanName, 0, Some(120));
bounded_string!(ReviewSpanPreview, 0, Some(240));
bounded_string!(ReviewVerdictSummary, 0, Some(300));
bounded_string!(StepLabel, 0, Some(200));
bounded_string!(StepModel, 0, Some(200), default = "");
bounded_string!(StepPurpose, 0, Some(40), default = "");
