# generated by datamodel-codegen:
#   filename:  lens.v1.json

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class LensV1(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )


class ApiError(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
    detail: str = Field(..., title="Detail")
    code: Literal[
        "dataset_not_found",
        "revision_not_found",
        "run_not_found",
        "run_closed",
        "unknown_case",
        "contract_version",
        "unauthorized",
    ] = Field(..., title="Code")


class CalledBefore(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
    kind: Literal["called_before"] = Field(default="called_before", title="Kind")
    first: str = Field(..., min_length=1, title="First")
    then: str = Field(..., min_length=1, title="Then")


class CaseDiff(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
    case_id: str = Field(..., title="Case Id")
    title: str = Field(..., title="Title")
    critical: bool = Field(..., title="Critical")
    baseline_url: str = Field(..., title="Baseline Url")
    candidate_url: str = Field(..., title="Candidate Url")


class CaseError(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
    type: str = Field(..., title="Type")
    message: str = Field(..., max_length=2000, title="Message")


class Gate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
    regressions: int | None = Field(default=0, title="Regressions")
    critical: int | None = Field(default=0, title="Critical")
    pass_rate: float | None = Field(default=None, ge=0.0, le=1.0, title="Pass Rate")
    cost_per_case: float | None = Field(default=None, ge=0.0, title="Cost Per Case")
    min: Mapping[str, float] = Field(default={}, title="Min")


class GateResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
    passed: bool = Field(..., title="Passed")
    reasons: Sequence[str] = Field(default=[], title="Reasons")


class Judge(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
    kind: Literal["judge"] = Field(default="judge", title="Kind")
    prompt: str = Field(..., min_length=1, title="Prompt")
    model: str = Field(default="", title="Model")


class ResolvedDataset(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
    id: str = Field(..., title="Id")
    name: str = Field(..., title="Name")
    revision: int = Field(..., title="Revision")


class Summary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
    passed: int = Field(..., title="Passed")
    total: int = Field(..., title="Total")
    pass_rate: float = Field(..., title="Pass Rate")
    cost_per_case: float = Field(..., title="Cost Per Case")
    scores: Mapping[str, float] = Field(..., title="Scores")
    errors: int = Field(..., title="Errors")
    baseline_run_id: str | None = Field(..., title="Baseline Run Id")
    baseline_version: str | None = Field(..., title="Baseline Version")
    regressions: Sequence[CaseDiff] = Field(..., title="Regressions")
    fixed: Sequence[CaseDiff] = Field(..., title="Fixed")
    gate: GateResult


class TaskCompleted(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
    kind: Literal["task_completed"] = Field(default="task_completed", title="Kind")


class TraceRef(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
    attribute: Literal["session.id", "trace_id"] = Field(default="session.id", title="Attribute")
    value: str = Field(..., min_length=1, title="Value")


class CaseResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
    trace: TraceRef | None = None
    error: CaseError | None = None
    cost_usd: float | None = Field(default=None, ge=0.0, title="Cost Usd")
    duration_ms: int | None = Field(default=None, ge=0, title="Duration Ms")


class CreateEvalRun(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
    eval: str = Field(..., min_length=1, pattern="^[a-z0-9][a-z0-9_-]*$", title="Eval")
    agent: str = Field(..., min_length=1, title="Agent")
    dataset_id: str = Field(..., title="Dataset Id")
    revision: int = Field(..., ge=1, title="Revision")
    case_ids: Sequence[str] | None = Field(default=None, title="Case Ids")
    version: str = Field(..., min_length=1, title="Version")
    branch: str = Field(..., min_length=1, title="Branch")
    pr: int | None = Field(default=None, title="Pr")
    ci_url: str = Field(default="", title="Ci Url")
    trials: int = Field(default=1, ge=1, le=10, title="Trials")
    scorers: Sequence[Annotated[TaskCompleted | CalledBefore | Judge, Field(discriminator="kind")]] = Field(
        ..., min_length=1, title="Scorers"
    )
    gate: Gate = Field(
        default={
            "regressions": 0,
            "critical": 0,
            "pass_rate": None,
            "cost_per_case": None,
            "min": {},
        },
        validate_default=True,
    )
    timeout_per_trial_ms: int = Field(default=1200000, gt=0, le=18446744073709551615, title="Timeout Per Trial Ms")


class EvalRun(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
    id: str = Field(..., title="Id")
    status: Literal["running", "scoring", "done", "failed"] = Field(..., title="Status")
    eval: str = Field(..., title="Eval")
    agent: str = Field(..., title="Agent")
    version: str = Field(..., title="Version")
    branch: str = Field(..., title="Branch")
    pr: int | None = Field(..., title="Pr")
    url: str = Field(..., title="Url")
    expected_trials: int = Field(..., title="Expected Trials")
    received_trials: int = Field(..., title="Received Trials")
    summary: Summary | None = None
    failure: str = Field(default="", title="Failure")
