# generated by datamodel-codegen:
#   filename:  lens.v1.json

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class LensEvalContract(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )


class CaseDiff(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
    baseline_url: str
    candidate_url: str
    case_id: str
    critical: bool
    title: str


class CaseError(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
    message: str = Field(..., max_length=2000)
    type: str


class Gate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
    cost_per_case: float | None = Field(default=None, ge=0.0)
    critical: int | None = Field(default=0, ge=0, le=18446744073709551615)
    min: Mapping[str, float] = {}
    pass_rate: float | None = Field(default=None, ge=0.0, le=1.0)
    regressions: int | None = Field(default=0, ge=0, le=18446744073709551615)


class GateResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
    passed: bool
    reasons: Sequence[str] = []


class ResolvedDataset(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
    id: str
    name: str
    revision: int = Field(..., ge=0, le=18446744073709551615)


class TaskCompleted(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
    kind: Literal["task_completed"]


class CalledBefore(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
    first: str = Field(..., min_length=1)
    kind: Literal["called_before"]
    then: str = Field(..., min_length=1)


class Judge(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
    kind: Literal["judge"]
    model: str = ""
    prompt: str = Field(..., min_length=1)


class ScorerCheck(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
    passed: bool
    scorer: str


class Summary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
    baseline_run_id: str | None = None
    baseline_version: str | None = None
    cost_per_case: float
    errors: int = Field(..., ge=0, le=18446744073709551615)
    fixed: Sequence[CaseDiff]
    gate: GateResult
    pass_rate: float
    passed: int = Field(..., ge=0, le=18446744073709551615)
    regressions: Sequence[CaseDiff]
    scores: Mapping[str, float]
    total: int = Field(..., ge=0, le=18446744073709551615)


class ToolStep(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
    end_ns: int
    name: str
    ok: bool
    start_ns: int
    tool_name: str


class TraceRef(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
    attribute: Literal["session.id", "trace_id"] = "session.id"
    value: str = Field(..., min_length=1)


class TrialSteps(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
    checks: Sequence[ScorerCheck]
    error: str | None = None
    steps: Sequence[ToolStep]
    trial: int = Field(..., ge=0, le=4294967295)


class ApiError(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
    code: Literal[
        "dataset_not_found",
        "revision_not_found",
        "run_not_found",
        "eval_not_found",
        "run_closed",
        "unknown_case",
        "contract_version",
        "unauthorized",
    ]
    detail: str


class CaseResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
    cost_usd: float | None = Field(default=None, ge=0.0)
    duration_ms: int | None = Field(default=None, ge=0, le=18446744073709551615)
    error: CaseError | None = None
    trace: TraceRef | None = None


class CreateEvalRun(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
    agent: str = Field(..., min_length=1)
    branch: str = Field(..., min_length=1)
    case_ids: Sequence[str] | None = None
    ci_url: str = ""
    dataset_id: str
    eval: str = Field(..., min_length=1, pattern="^[a-z0-9][a-z0-9_-]*$")
    gate: Gate = Field(
        default={
            "cost_per_case": None,
            "critical": 0,
            "min": {},
            "pass_rate": None,
            "regressions": 0,
        },
        validate_default=True,
    )
    pr: int | None = Field(default=None, ge=0, le=18446744073709551615)
    revision: int = Field(..., ge=1, le=18446744073709551615)
    scorers: Sequence[TaskCompleted | CalledBefore | Judge] = Field(..., min_length=1)
    timeout_per_trial_ms: int = Field(default=1200000, ge=1, le=18446744073709551615)
    trials: int = Field(default=1, ge=1, le=10)
    version: str = Field(..., min_length=1)


class EvalRun(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
    agent: str
    branch: str
    ci_url: str = ""
    eval: str
    expected_trials: int = Field(..., ge=0, le=18446744073709551615)
    failure: str = ""
    id: str
    pr: int | None = Field(default=None, ge=0, le=18446744073709551615)
    received_trials: int = Field(..., ge=0, le=18446744073709551615)
    status: Literal["running", "scoring", "done", "failed"]
    summary: Summary | None = None
    url: str
    version: str


class EvalSpec(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
    agent: str = Field(..., min_length=1)
    baseline: str = Field(default="main", min_length=1)
    dataset_id: str = Field(..., min_length=1)
    gate: Gate = Field(
        default={
            "cost_per_case": None,
            "critical": 0,
            "min": {},
            "pass_rate": None,
            "regressions": 0,
        },
        validate_default=True,
    )
    revision: int | None = Field(default=None, ge=1, le=18446744073709551615)
    scorers: Sequence[TaskCompleted | CalledBefore | Judge] = Field(..., min_length=1)
    timeout_per_trial_ms: int = Field(default=1200000, ge=1, le=18446744073709551615)
    trials: int = Field(default=1, ge=1, le=10)


class RunCase(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
    case_id: str
    critical: bool
    passed: bool | None = None
    title: str
    trials: Sequence[TrialSteps]


class EvalDefinition(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
    name: str = Field(..., min_length=1, pattern="^[a-z0-9][a-z0-9_-]*$")
    spec: EvalSpec
    updated_at: str
