from collections.abc import Awaitable, Callable

def validate_eval(spec: str) -> None: ...
def settings(root: str) -> str: ...
def execution(root: str, ci: bool) -> str: ...
def endpoint(value: str) -> str: ...
def redact(value: str) -> str: ...
def parse_cli(arguments: list[str]) -> str: ...
def render(report: str, format: str) -> str: ...
def control(command: str) -> str: ...
def diagnose(specs: str, ci: bool) -> Awaitable[str]: ...
def evaluate(
    spec: str, project: str, endpoint: str, key: str, context: str, callback: Callable[[str], Awaitable[str]]
) -> Awaitable[str]: ...
def run_named(name: str, endpoint: str, key: str, context: str, root: str) -> Awaitable[str]: ...
def subset_name(name: str, finding: str | None, case_ids: tuple[str, ...] | None) -> str: ...
